-- AlterTable
ALTER TABLE "public"."tb_user" ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "birth_date" DROP NOT NULL,
ALTER COLUMN "tel" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "roleId" SET DEFAULT 1;
